#cloud-config

# Upgrade the instance on first boot
apt_upgrade: true

# Update apt database on first boot
apt_update: true

apt_sources:
  - source: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main"
    keyid: 417A0893 # GPG key ID published on a key server
    filename: az-cli.list

# Install additional packages on first boot
packages:
  - curl
  - git-core
  - nginx
  - nodejs
  - apt-transport-https
  - ca-certificates
  - azure-cli

# Commands to prepare the Habitat development environment
runcmd:
  - curl -sSL https://get.rvm.io | bash -s stable --rails
  - usermod -a -G rvm deploy

# Print message at the end of cloud-init job
final_message: "The system is up, after $UPTIME seconds"