development:
  clients:
    default:
      database: todo_dev
      hosts:
        - <%= ENV['DB_HOST'] || 'localhost:27017' %>
test:
  clients:
    default:
      database: todo_test
      hosts:
        - <%= ENV['DB_HOST'] || 'localhost:27017' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  sessions:
    default:
      options:
        ssl: true
  clients:
    default:
      <% if Rails.env.production? %>
      <% docdb_name=`az documentdb list -g level1 --query "[?starts_with(name, 'level1')] | [0].name" -o tsv`.strip %>
      <% conn_strings=JSON.parse(`az documentdb list-connection-strings -g level1 -n '#{docdb_name}'`) %>
      uri: <%= conn_strings["connectionStrings"][0]["connectionString"] %>
      <% end %>
      options:
        # The default timeout is 5, which is the time in seconds
        # for a connection to time out.
        # We recommend 15 because it allows for plenty of time
        # in most operating environments.
        connect_timeout: 15